# Generated by Django 5.0.6 on 2024-06-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=35)),
                ('srollno', models.IntegerField()),
                ('csr', models.CharField(max_length=25)),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
    ]
